version: '3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
       - transport.host=127.0.0.1
       - http.host=0.0.0.0
       - xpack.security.enabled=false
    ports:
      - "9200:9200"
